#!/bin/bash
echo "Installing homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Installing dev tools"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
brew install git
brew install tmux
brew install neovim

echo "Install other apps"
brew cask install slack
brew cask install discord


echo "Installing fonts"
brew tap caskroom/fonts
brew cask install font-fira-code
brew cask install font-hack-nerd-font

echo "Symbolic linking dotfiles to their homes"
ln -sf ~/dotfiles/tmux/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/zsh/.zshrc ~/.zshrc
ln -sf ~/dotfiles/nvim/init.vim ~/.config/nvim/init.vim
ln -sf ~/dotfiles/kitty/kitty.conf ~/.config/kitty/kitty.conf

echo "Complete!"
