format = """
$battery[░▒▓](#e0def4)[  ](bg:#e0def4 fg:#31748f)\
[](bg:#31748f fg:#e0def4)\
$directory\
[](fg:#31748f bg:#6e6a86)\
$git_branch\
$git_status\
[](fg:#6e6a86 bg:#26233a)\
$version\
[](fg:#26233a bg:#191724)\
$time\
[ ](fg:#191724)\
$fill\
(\n$status$cmd_duration)
\n$character
"""

[character]
format  = '[➜](bold #31748f) '

[directory]
style = "fg:#e0def4 bg:#31748f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[fill]
style = "bold #c4a7e7"

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#9ccfd8 bg:#6e6a86)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#c4a7e7 bg:#6e6a86)]($style)'

[time]
disabled = false
use_12hr = true
format = '[[  $time ](fg:#c4a7e7 bg:#191724)]($style)'

