name: Setup Nix
description: Install Nix and enable public binary caches

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v22

    - name: Configure public caches
      uses: cachix/cachix-action@v15
      with:
        name: nix-community
        extraPullNames: niri
        skipPush: "true"
