import = ["rocks-common.toml"]

[plugins]
"rustaceanvim" = "9.2.1"

[plugins."nvim-java"]
git = "nvim-java/nvim-java"
rev = "v4.1.2"

[plugins."tree-sitter-mog"]
dir = "~/workspace/mog-private/packages/tree-sitter"
