# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version-rev"  # e.g. "1.0.0-0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.5.0" # rocks.nvim can also manage itself :D

# from plugins/init.lua
plenary = { git = "nvim-lua/plenary.nvim" }
nui = { git = "MunifTanjim/nui.nvim" }
nvim-web-devicons = { git = "nvim-tree/nvim-web-devicons" }

autoswap = { git = "gioele/vim-autoswap" }
colorizer = { git = "NvChad/nvim-colorizer.lua" }

# cmp.lua
nvim-cmp = { git = "hrsh7th/nvim-cmp" }
nvim-cmp-lsp = { git = "hrsh7th/cmp-nvim-lsp" }
nvim-cmp-buffer = { git = "hrsh7th/cmp-buffer" }
nvim-cmp-path = { git = "hrsh7th/cmp-path" }
nvim-cmp-cmdline = { git = "hrsh7th/cmp-cmdline" }
cmp-spell = { git = "f3fora/cmp-spell" }
luasnip = { git = "L3MON4D3/LuaSnip" }
nvim-autopairs = { git = "windwp/nvim-autopairs" }
copilot-lua = { git = "zbirenbaum/copilot.lua" }
copilot-cmp = { git = "zbirenbaum/copilot-cmp" }

# conjure.lua
conjure = { git = "Olical/conjure" }

# diagnostic.lua
trouble = { git = "folke/trouble.nvim" }

# git.lua
gitsigns = { git = "lewis6991/gitsigns.nvim" }

# hydra.lua
hydra = { git = "nvimtools/hydra.nvim" }
winshift-nvim = { git = "sindrets/winshift.nvim" }
smart-splits = { git = "mrjones2014/smart-splits.nvim" }
middleclass = { git = "anuvyklack/middleclass" }
animation-nvim = { git = "anuvyklack/animation.nvim" }
windows-nvim = { git = "anuvyklack/windows.nvim" }

# lsp.lua
lsp-zero = { git = "VonHeikemen/lsp-zero.nvim" }
mason = { git = "williamboman/mason.nvim" }
mason-lspconfig = { git = "williamboman/mason-lspconfig.nvim" }
nvim-lspconfig = { git = "neovim/nvim-lspconfig" }

# navigation.lua
flash = { git = "folke/flash.nvim" }

# neorg.lua
neorg = { git = "nvim-neorg/neorg" }
neorg-telescope = { git = "nvim-neorg/neorg-telescope" }
neorg-templates = { git = "pysan3/neorg-templates" }

# oatmeal.lua
oatmeal = { git = "dustinblackman/oatmeal.nvim" }

# oil.lua
oil = { git = "stevearc/oil.nvim" }

# statusline.lua
lualine = { git = "nvim-lualine/lualine.nvim" }
lualine-lsp-progress = { git = "arkav/lualine-lsp-progress" }

# telescope.lua
telescope = { git = "nvim-telescope/telescope.nvim" }
telescope-undo = { git = "debugloop/telescope-undo.nvim" }
# TODO: requires a compilation/build step
telescope-fzf-native = { git = "nvim-telescope/telescope-fzf-native.nvim" }

# theme.lua
rose-pine = { git = "rose-pine/neovim" }
auto-dark-mode = { git = "f-person/auto-dark-mode.nvim" }
indent-blankline = { git = "lukas-reineke/indent-blankline.nvim" }

# treesitter.lua
nvim-treesitter = { git = "nvim-treesitter/nvim-treesitter" }
nvim-ts-autotag = { git = "windwp/nvim-ts-autotag" }
nvim-treesitter-context = { git = "nvim-treesitter/nvim-treesitter-context" }
comment = { git = "numToStr/Comment.nvim" }
nvim-ts-context-commentstring = { git = "JoosepAlviste/nvim-ts-context-commentstring" }

# which-key.lua
which-key = { git = "folke/which-key.nvim" }

# zen.lua
zen-mode = { git = "folke/zen-mode.nvim" }
