[plugins]
"rocks.nvim" = "2.40.0"
"rocks-config.nvim" = "2.3.1"
"rocks-dev.nvim" = "1.7.0"
"rocks-git.nvim" = "2.2.0"
"rocks-treesitter.nvim" = "1.1.2"
"rocks-edit.nvim" = "scm"

# plugins for cmp bundle
#"nvim-cmp" = { git = "hrsh7th/nvim-cmp" }
# "cmp-nvim-lsp" = { git = "hrsh7th/cmp-nvim-lsp" }
"care.nvim" = { git = "max397574/care.nvim", rev = "df80439586a56394d4fcb99769be227760b52ad0" }
"care-cmp" = { git = "max397574/care-cmp" }
"cmp-buffer" = { git = "hrsh7th/cmp-buffer" }
"cmp-path" = { git = "hrsh7th/cmp-path" }
"cmp-cmdline" = { git = "hrsh7th/cmp-cmdline" }
"cmp-conjure" = { git = "PaterJason/cmp-conjure" }
"lsp-zero.nvim" = { git = "VonHeikemen/lsp-zero.nvim", rev = "v4.x" }
"luasnip" = "2.3.0"
"neorg" = "9.1.1"
"neorg-contexts" = { git = "max397574/neorg-contexts" }
"neorg-templates" = { git = "pysan3/neorg-templates" }
"neorg-worklog" = "1.3.4"
"neorg-telescope" = "1.2.2"
"oil.nvim" = "2.12.2"
"conjure" = "4.52.2"
"nvim-autopairs" = "scm"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"
"nfnl" = { git = "Olical/nfnl" }
"zen-mode.nvim" = "scm"
"catppuccin" = { git = "catppuccin/nvim", rev = "1.9.0" }
"headlines.nvim" = "scm"
"which-key.nvim" = "3.13.2"
"indent-blankline.nvim" = "3.7.2"
"telescope.nvim" = "scm"
"telescope-undo.nvim" = "scm"
"telescope-fzf-native.nvim" = { git = "nvim-telescope/telescope-fzf-native.nvim", build = "make" }
"nvim-web-devicons" = { version = "0.100", config = false }
"lualine.nvim" = "scm"
"alpha-nvim" = "scm"
"bufdelete.nvim" = "scm"
# "flash.nvim" = "1.18.2"
"nvim-lspconfig" = "1.0.0"
"vim-autoswap" = { git = "gioele/vim-autoswap" }
"nvim-colorizer" = { git = "NvChad/nvim-colorizer.lua" }
"nvim-ts-autotag" = "scm"
"ts-comments.nvim" = { git = "folke/ts-comments.nvim" }
"smart-splits.nvim" = "1.6.0"
"middleclass" = { git = "anuvyklack/middleclass" }
"animation.nvim" = { git = "anuvyklack/animation.nvim" }
"windows.nvim" = { git = "anuvyklack/windows.nvim" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }
"lazygit.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
tree-sitter-json = "scm"
tree-sitter-javascript = "scm"
tree-sitter-toml = "scm"
tree-sitter-bash = "scm"
tree-sitter-css = "scm"
tree-sitter-comment = "scm"
tree-sitter-diff = "scm"
tree-sitter-fennel = "scm"
tree-sitter-fish = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-graphql = "scm"
tree-sitter-html = "scm"
tree-sitter-markdown = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-lua = "scm"
tree-sitter-python = "scm"
tree-sitter-query = "scm"
tree-sitter-rust = "scm"
tree-sitter-sql = "scm"
tree-sitter-svelte = "scm"
tree-sitter-tsx = "scm"
tree-sitter-typescript = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-nu = "scm"
tree-sitter-jsonc = "scm"
tree-sitter-yaml = "scm"
"nvim-treesitter" = { git = "nvim-treesitter/nvim-treesitter" }
"conform.nvim" = "8.1.0"
"trouble.nvim" = "3.6.0"
"helpview.nvim" = "1.1.0"
"mini.nvim" = "scm"
"otter.nvim" = "2.5.0"

#[bundles.cmp]
#items = [
#"nvim-cmp",
#"cmp-nvim-lsp",
#"cmp-buffer",
#"cmp-path",
#"cmp-cmdline",
#"cmp-conjure",
#"lsp-zero.nvim",
#"luasnip",
#]

[bundles.care]
items = [
  "care.nvim",
  "care-cmp",
  "cmp-buffer",
  "cmp-path",
  "cmp-cmdline",
  "cmp-conjure",
  "lsp-zero.nvim",
  "luasnip",
  "nvim-autopairs",
]


[bundles.lsp]
items = [
  "lsp-zero.nvim",
  "mason.nvim",
  "mason-lspconfig.nvim",
  "nvim-lspconfig",
]

[bundles.treesitter]
items = ["nvim-treesitter", "nvim-ts-autotag"]

[bundles.indent-lines]
items = ["mini.nvim", "indent-blankline.nvim"]

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[config]
auto_setup = true
colorscheme = "catppuccin"


[config.options]
cursorline = true
expandtab = true
foldlevelstart = 99
number = true
shiftwidth = 2
smartindent = true
tabstop = 2
timeout = true
timeoutlen = 300
