[config]
auto_setup = true

# Plugins I didn't install
# nvim-pack/nvim-spectre
# dustinblackman/oatmeal.nvim

# TODO: plugins files to migrate:
# image, diagnostic, conjure

[plugins]
"rocks.nvim" = "2.35.2"
"rocks-config.nvim" = "2.1.4"
"rocks-dev.nvim" = "1.2.4"
"rocks-git.nvim" = "2.0.0"
"rocks-treesitter.nvim" = "scm"

# plugins for cmp bundle
"nvim-cmp" = { git = "hrsh7th/nvim-cmp" }
"cmp-nvim-lsp" = { git = "hrsh7th/cmp-nvim-lsp" }
"cmp-buffer" = { git = "hrsh7th/cmp-buffer" }
"cmp-path" = { git = "hrsh7th/cmp-path" }
"cmp-cmdline" = { git = "hrsh7th/cmp-cmdline" }
"cmp-conjure" = { git = "PaterJason/cmp-conjure" }
"copilot.lua" = "scm"
"lsp-zero.nvim" = { git = "VonHeikemen/lsp-zero.nvim", branch = "v3.x" }
"luasnip" = "2.3.0"
"neorg" = { version = "8.9.0" }
"neodev.nvim"= "scm"
"oil.nvim" = "scm"
"conjure" = { git = "Olical/conjure" }
"nvim-autopairs" = "scm"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.29.0"
"nfnl" = { git = "Olical/nfnl" }
"neorg-templates" = { git = "pysan3/neorg-templates" }
"zen-mode.nvim" = "scm"
"rose-pine" = "scm"
"headlines.nvim" = "scm"
"neorg-telescope" = "1.1.0"
"which-key.nvim" = "3.3.0"
"indent-blankline.nvim" = { version = "3.7.1" }
"telescope.nvim" = "scm"
"telescope-undo.nvim" = "scm"
"telescope-fzf-native.nvim" = { git = "nvim-telescope/telescope-fzf-native.nvim", build = "make"}
"nvim-web-devicons" = "0.100"
"lualine.nvim" = "scm"
"alpha-nvim" = "scm"
"bufdelete.nvim" = "scm"
# "flash.nvim" = "1.18.2"
"nvim-lspconfig" = "0.1.8"
"vim-autoswap" = { git = "gioele/vim-autoswap"}
"nvim-colorizer" = { git = "NvChad/nvim-colorizer.lua" }
"nvim-ts-autotag" = "scm"
"ts-comments.nvim" = { git = "folke/ts-comments.nvim" }
"hydra.nvim" = "1.0.2"
"smart-splits.nvim" = "1.5.0"
"middleclass" = { git = "anuvyklack/middleclass" }
"animation.nvim" = { git = "anuvyklack/animation.nvim" }
"windows.nvim" = { git = "anuvyklack/windows.nvim" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }
"lazygit.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
tree-sitter-json = "scm"
tree-sitter-javascript = "scm"
tree-sitter-toml = "scm"
tree-sitter-css = "scm"
tree-sitter-comment = "scm"
tree-sitter-diff = "scm"
tree-sitter-fennel = "scm"
tree-sitter-fish = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-graphql = "scm"
tree-sitter-html = "scm"
tree-sitter-markdown = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-lua = "scm"
tree-sitter-python = "scm"
tree-sitter-rust = "scm"
tree-sitter-sql = "scm"
tree-sitter-svelte = "scm"
tree-sitter-tsx = "scm"
tree-sitter-typescript = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-nu = { git = "nushell/tree-sitter-nu", build = ":TSUpdate" }
tree-sitter-jsonc = "scm"
# rustaceanvim = "4.26.1"
# nvim-treesitter-legacy-api = "0.9.2"
"nvim-treesitter" = { git = "nvim-treesitter/nvim-treesitter" }

[bundles.cmp]
items = [
  "nvim-cmp",
  "cmp-nvim-lsp",
  "cmp-buffer",
  "cmp-path",
  "cmp-cmdline",
  "cmp-conjure",
  "copilot.lua",
  "lsp-zero.nvim",
  "luasnip"
]

[bundls.treesitter]
items = [
  "nvim-treesitter",
#  "nvim-treesitter-legacy-api",
  "nvim-ts-autotag"
]

[bundles.no-setup]
items = [
  "nvim-web-devicons"
]

[treesitter]
auto_highlight = "all"
auto_install = "prompt"
