[config]
plugins_dir = "plugins/"
auto_setup = true

# Plugins I didn't install
# akinsho/toggleterm.nvim
# nvim-pack/nvim-spectre
# dustinblackman/oatmeal.nvim

# TODO: plugins files to migrate:
# image, diagnostic, conjure

# TODO: read and fix lspconfig plugins file error
[plugins]
"rocks.nvim" = "2.29.2"
# "rocks-config.nvim" = { dir = "~/workspace/github/rocks-config.nvim" }
"rocks-config.nvim" = "1.6.0"
"neorg" = "8.5.0"
"rocks-git.nvim" = "1.5.0"
"rocks-treesitter.nvim" = "scm"
"oil.nvim" = "2.8.0"
"nvim-cmp" = { git = "hrsh7th/nvim-cmp" }
"cmp-nvim-lsp" = { git = "hrsh7th/cmp-nvim-lsp" }
"cmp-buffer" = { git = "hrsh7th/cmp-buffer" }
"cmp-path" = { git = "hrsh7th/cmp-path" }
"cmp-cmdline" = { git = "hrsh7th/cmp-cmdline" }
"luasnip" = "2.3.0"
"lsp-zero.nvim" = { git = "VonHeikemen/lsp-zero.nvim", branch = "v3.x" }
"conjure" = { git = "Olical/conjure" }
"cmp-conjure" = { git = "PaterJason/cmp-conjure" }
"nvim-autopairs" = "scm"
"copilot.lua" = "scm"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.28.0"
"nfnl" = { git = "Olical/nfnl" }
"nvim-treesitter" = { git = "nvim-treesitter/nvim-treesitter" } 
"neorg-templates" = { git = "pysan3/neorg-templates" }
"zen-mode.nvim" = "scm"
"rose-pine" = "scm"
"headlines.nvim" = "4.0.1"
"neorg-telescope" = "1.1.0"
"which-key.nvim" = "1.6.0"
"indent-blankline.nvim" = { version = "3.5.4", nosetup = true }
"telescope.nvim" = "scm"
"telescope-undo.nvim" = "scm"
"telescope-fzf-native.nvim" = { git = "nvim-telescope/telescope-fzf-native.nvim", build = "make"}
"nvim-web-devicons" = "0.99"
"lualine.nvim" = "scm"
"alpha-nvim" = "scm"
"bufdelete.nvim" = "scm"
# "flash.nvim" = "1.18.2"
"nvim-lspconfig" = "0.1.7"
"vim-autoswap" = { git = "gioele/vim-autoswap"}
"nvim-colorizer" = { git = "NvChad/nvim-colorizer.lua" }
"nui.nvim" = "0.3.0"
"plenary.nvim" = "scm"
"nvim-ts-autotag" = "scm"
"ts-comments.nvim" = { git = "folke/ts-comments.nvim" }
"hydra.nvim" = "1.0.2"
"smart-splits.nvim" = "1.4.0"
"middleclass" = { git = "anuvyklack/middleclass" }
"animation.nvim" = { git = "anuvyklack/animation.nvim" }
"windows.nvim" = { git = "anuvyklack/windows.nvim" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }
"lazygit.nvim" = "scm"
"rocks-dev.nvim" = "1.2.1"

[treesitter]
auto_highlight = [
  "comment",
  "css",
  "diff",
  "fennel",
  "fish",
  "gitignore",
  "graphql",
  "html",
  "json",
  "markdown",
  "markdown_inline",
  # someday 🙏
  # norg
  "lua",
  "python",
  "rust",
  "sql",
  "svelte",
  "toml",
  "tsx",
  "typescript",
  "vimdoc"
]
auto_install = true
