[config]
auto_setup = true

# Plugins I didn't install
# nvim-pack/nvim-spectre
# dustinblackman/oatmeal.nvim

# TODO: plugins files to migrate:
# image, diagnostic, conjure

[plugins]
"rocks.nvim" = "2.36.1"
"rocks-config.nvim" = "2.2.0"
"rocks-dev.nvim" = "1.3.0"
"rocks-git.nvim" = "2.0.1"
"rocks-treesitter.nvim" = "1.0.3"

# plugins for cmp bundle
"nvim-cmp" = { git = "hrsh7th/nvim-cmp" }
"cmp-nvim-lsp" = { git = "hrsh7th/cmp-nvim-lsp" }
"cmp-buffer" = { git = "hrsh7th/cmp-buffer" }
"cmp-path" = { git = "hrsh7th/cmp-path" }
"cmp-cmdline" = { git = "hrsh7th/cmp-cmdline" }
"cmp-conjure" = { git = "PaterJason/cmp-conjure" }
"copilot.lua" = "scm"
"lsp-zero.nvim" = { git = "VonHeikemen/lsp-zero.nvim", branch = "v3.x" }
"luasnip" = "2.3.0"
"neorg" = "9.1.1"
"neorg-templates" = { git = "pysan3/neorg-templates" }
"neorg-worklog" = "1.2.2"
"neorg-telescope" = "1.2.2"
"oil.nvim" = "2.11.0"
"conjure" = "4.52.2"
"nvim-autopairs" = "scm"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.30.0"
"nfnl" = { git = "Olical/nfnl" }
"zen-mode.nvim" = "scm"
"catppuccin" = { git = "catppuccin/nvim" }
"headlines.nvim" = "scm"
"which-key.nvim" = "3.7.0"
"indent-blankline.nvim" = "3.7.1"
"telescope.nvim" = "scm"
"telescope-undo.nvim" = "scm"
"telescope-fzf-native.nvim" = { git = "nvim-telescope/telescope-fzf-native.nvim", build = "make" }
"nvim-web-devicons" = { version = "0.100", config = false }
"lualine.nvim" = "scm"
"alpha-nvim" = "scm"
"bufdelete.nvim" = "scm"
# "flash.nvim" = "1.18.2"
"nvim-lspconfig" = "0.1.8"
"vim-autoswap" = { git = "gioele/vim-autoswap" }
"nvim-colorizer" = { git = "NvChad/nvim-colorizer.lua" }
"nvim-ts-autotag" = "scm"
"ts-comments.nvim" = { git = "folke/ts-comments.nvim" }
"hydra.nvim" = "1.0.2"
"smart-splits.nvim" = "1.5.0"
"middleclass" = { git = "anuvyklack/middleclass" }
"animation.nvim" = { git = "anuvyklack/animation.nvim" }
"windows.nvim" = { git = "anuvyklack/windows.nvim" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }
"lazygit.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
tree-sitter-json = "scm"
tree-sitter-javascript = "scm"
tree-sitter-toml = "scm"
tree-sitter-css = "scm"
tree-sitter-comment = "scm"
tree-sitter-diff = "scm"
tree-sitter-fennel = "scm"
tree-sitter-fish = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-graphql = "scm"
tree-sitter-html = "scm"
tree-sitter-markdown = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-lua = "scm"
tree-sitter-python = "scm"
tree-sitter-query = "scm"
tree-sitter-rust = "scm"
tree-sitter-sql = "scm"
tree-sitter-svelte = "scm"
tree-sitter-tsx = "scm"
tree-sitter-typescript = "scm"
tree-sitter-vimdoc = "scm"
# tree-sitter-nu = { git = "nushell/tree-sitter-nu", build = ":TSUpdate" }
tree-sitter-jsonc = "scm"
tree-sitter-yaml = "scm"
"nvim-treesitter" = { git = "nvim-treesitter/nvim-treesitter" }
"conform.nvim" = "7.0.0"

[bundles.cmp]
items = [
  "nvim-cmp",
  "cmp-nvim-lsp",
  "cmp-buffer",
  "cmp-path",
  "cmp-cmdline",
  "cmp-conjure",
  "copilot.lua",
  "lsp-zero.nvim",
  "luasnip",
]

[bundles.lsp]
items = [
  "lsp-zero.nvim",
  "mason.nvim",
  "mason-lspconfig.nvim",
  "nvim-lspconfig",
]

[bundls.treesitter]
items = ["nvim-treesitter", "nvim-ts-autotag"]

[treesitter]
auto_highlight = "all"
auto_install = "prompt"
