[plugins]
"rocks.nvim" = "2.41.1"
"rocks-config.nvim" = "3.0.0"
"rocks-dev.nvim" = "1.7.0"
"rocks-git.nvim" = "2.5.1"
"rocks-treesitter.nvim" = "1.1.3"
"rocks-edit.nvim" = "scm"
"luasnip" = "2.3.0"
"nvim-autopairs" = "scm"

# Neorg
"neorg" = "9.1.1"
"neorg-worklog" = "1.3.4"
"neorg-telescope" = "1.2.2"
"neorg-interim-ls" = "1.2.1"

"oil.nvim" = "2.12.2"
"conjure" = "4.52.2"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"
"zen-mode.nvim" = "scm"
"catppuccin" = { git = "catppuccin/nvim", rev = "v1.9.0" }
"headlines.nvim" = "scm"
"which-key.nvim" = "3.13.3"
"indent-blankline.nvim" = "3.8.3"
"telescope.nvim" = "scm"
"telescope-undo.nvim" = "scm"
"nvim-web-devicons" = { version = "0.100", config = false }
"lualine.nvim" = "scm"
"alpha-nvim" = "scm"
"bufdelete.nvim" = "scm"
# "flash.nvim" = "1.18.2"
"nvim-lspconfig" = "1.0.0"
"nvim-ts-autotag" = "scm"
"smart-splits.nvim" = "1.6.0"
"lazygit.nvim" = "scm"
"rocks-lazy.nvim" = "scm"
tree-sitter-json = "0.0.30"
tree-sitter-javascript = "0.0.31"
tree-sitter-toml = "0.0.30"
tree-sitter-bash = "0.0.32"
tree-sitter-css = "0.0.30"
tree-sitter-comment = "0.0.29"
tree-sitter-diff = "0.0.31"
tree-sitter-fennel = "0.0.29"
tree-sitter-gitignore = "0.0.29"
tree-sitter-graphql = "0.0.29"
tree-sitter-html = "0.0.30"
tree-sitter-markdown = "0.0.35"
tree-sitter-markdown_inline = "0.0.35"
tree-sitter-nix = "0.0.46"
tree-sitter-lua = "0.0.31"
tree-sitter-python = "0.0.30"
tree-sitter-query = "0.0.29"
tree-sitter-rust = "0.0.33"
tree-sitter-sql = "0.0.31"
tree-sitter-svelte = "0.0.32"
tree-sitter-tsx = "0.0.30"
tree-sitter-typescript = "0.0.30"
tree-sitter-vimdoc = "0.0.31"
tree-sitter-nu = "scm"
tree-sitter-jsonc = "0.0.29"
tree-sitter-yaml = "0.0.29"
"conform.nvim" = "8.1.0"
"trouble.nvim" = "3.6.0"
"helpview.nvim" = "1.1.0"
"mini.nvim" = "scm"
"otter.nvim" = "2.5.0"
nvim-treesitter-legacy-api = "0.9.2"
nvim-treesitter-context = "scm"

[plugins."lazydev.nvim"]
git = "folke/lazydev.nvim"
rev = "v1.8.0"

[plugins."care.nvim"]
git = "max397574/care.nvim"
rev = "394d71f2543d9e2ca4f87ad43fa2ff0b8efc29a5"

[plugins."care-cmp"]
git = "max397574/care-cmp"
rev = "72cbb457e2ff246fd672d524270effe46f92ce4f"


[plugins."cmp-buffer"]
git = "hrsh7th/cmp-buffer"
rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa"

[plugins."cmp-path"]
git = "hrsh7th/cmp-path"
rev = "91ff86cd9c29299a64f968ebb45846c485725f23"

[plugins."cmp-cmdline"]
git = "hrsh7th/cmp-cmdline"
rev = "d250c63aa13ead745e3a40f61fdd3470efde3923"

[plugins."cmp-conjure"]
git = "PaterJason/cmp-conjure"
rev = "8c9a88efedc0e5bf3165baa6af8a407afe29daf6"

[plugins."neorg-contexts"]
git = "max397574/neorg-contexts"
rev = "8ae58b646700b8bc2d3bc1346c96835ceb71d884"

[plugins."neorg-templates"]
git = "pysan3/neorg-templates"
rev = "v2.0.3"

[plugins."nfnl"]
git = "Olical/nfnl"
rev = "v1.0.0"

[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"
rev = "cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b"
build = "make"

[plugins."vim-autoswap"]
git = "gioele/vim-autoswap"
rev = "v0.3"

[plugins."nvim-colorizer"]
git = "NvChad/nvim-colorizer.lua"
rev = "0671e0eabc6842676d3310370e8fae4e1c51d7f9"

[plugins."ts-comments.nvim"]
git = "folke/ts-comments.nvim"
rev = "v1.5.0"

[plugins."middleclass"]
git = "anuvyklack/middleclass"
rev = "9fab4d5bca67262614960960ca35c4740eb2be2c"

[plugins."animation.nvim"]
git = "anuvyklack/animation.nvim"
rev = "fb77091ab72ec9971aee0562e7081182527aaa6a"

[plugins."windows.nvim"]
git = "anuvyklack/windows.nvim"
rev = "c7492552b23d0ab30325e90b56066ec51242adc8"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
rev = "v3.0.0"

[bundles.care]
items = [
  "care.nvim",
  "care-cmp",
  "cmp-buffer",
  "cmp-path",
  "cmp-cmdline",
  "cmp-conjure",
  "luasnip",
  "nvim-autopairs",
]


[bundles.lsp]
items = [
  "mason.nvim",
  "mason-lspconfig.nvim",
  "nvim-lspconfig",
  "lsp_lines.nvim",
]

[bundles.treesitter]
items = ["nvim-treesitter-context", "nvim-ts-autotag"]

[bundles.indent-lines]
items = ["mini.nvim", "indent-blankline.nvim"]

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[config]
auto_setup = true
colorscheme = "catppuccin"


[config.options]
cursorline = true
expandtab = true
foldlevelstart = 99
guifont = "MonoLisa Nerd Font"
number = true
shiftwidth = 2
smartindent = true
tabstop = 2
timeout = true
timeoutlen = 300
equalalways = false
winwidth = 10
winminwidth = 10
